variables:
  ascName: OryxMCR
  acrName: oryxdevmcr.azurecr.io
  skipComponentGovernanceDetection: true

stages:
- stage: Build
  jobs:
  - template: templates/_buildimageBasesJobTemplate.yml
    parameters:
      displayName: Node Runtime Base Images
      scriptPath: ./build/buildRunTimeImageBases.sh
      imageDir: node
      artifactsFileName: node-runtimeimage-bases.txt

  - template: templates/_buildimageBasesJobTemplate.yml
    parameters:
      displayName: DotNetCore Runtime Base Images
      scriptPath: ./build/buildRunTimeImageBases.sh
      imageDir: dotnetcore
      artifactsFileName: dotnetcore-runtimeimage-bases.txt

  - template: templates/_buildimageBasesJobTemplate.yml
    parameters:
      displayName: Python Build Base Images
      scriptPath: ./build/buildBuildImageBases.sh
      imageDir: python
      artifactsFileName: python-buildimage-bases.txt

  - template: templates/_buildimageBasesJobTemplate.yml
    parameters:
      displayName: PHP Build Base Images
      scriptPath: ./build/buildBuildImageBases.sh
      imageDir: php
      artifactsFileName: php-buildimage-bases.txt

  - template: templates/_buildimageBasesJobTemplate.yml
    parameters:
      displayName: PHP Runtime Base Images
      scriptPath: ./build/buildRunTimeImageBases.sh
      imageDir: php
      artifactsFileName: php-runtimeimage-bases.txt

  - template: templates/_buildimageBasesJobTemplate.yml
    parameters:
      displayName: Yarn Cache Image
      scriptPath: ./build/buildBuildImageBases.sh
      imageDir: yarn-cache
      artifactsFileName: yarn-cache-buildimage-bases.txt

- stage: Release
  displayName: Release Stage
  condition: or(succeeded(), failed())
  jobs:
  - template: templates/_releaseBaseImagesJobTemplate.yml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - images/runtime/node
    - images/build/python
    - images/build/php
    - images/runtime/php
    - images/build/yarn-cache
    - build/
    - vsts/
